#!/bin/bash

basedir=`dirname $0`

if type -p ipython2; then
    _ipython=ipython2
    isexplicitpython2=true
    echo "Found iPython2 executable"
elif type -p ipython; then
    _ipython=ipython
    isexplicitpython2=false
    echo "Found iPython executable, hopefully using Python2"
else
    echo "no ipython executable found in PATH"
fi

if [[ "$_ipython" ]]; then
    version=$("$_ipython" --version 2>/dev/null)
    # Old ipython versions have -Version argument in stead of --version.
    # Determine from the length of the return string if the help-text
    # is returned instead of the version number.
    if [[ ${#version} -gt 10 ]]; then
        version=$("$_ipython" -Version)
    fi
    if [[ isexplicitpython2 ]]; then
        ipython2 --gui=gtk -i $basedir/source/qtlab_shell.py -- "$@"
    elif [[ "$version" -lt "0.11" ]]; then
        ipython -gthread $basedir/source/qtlab_shell.py -- "$@"
    else
        ipython --gui=gtk -i $basedir/source/qtlab_shell.py -- "$@"
    fi
fi
